/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSolutionsRouteImport } from './routes/_site.solutions'
import { Route as SiteProjectsRouteImport } from './routes/_site.projects'
import { Route as SiteIndustriesRouteImport } from './routes/_site.industries'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSolutionsRoute = SiteSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIndustriesRoute = SiteIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/industries': typeof SiteIndustriesRoute
  '/projects': typeof SiteProjectsRoute
  '/solutions': typeof SiteSolutionsRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/industries': typeof SiteIndustriesRoute
  '/projects': typeof SiteProjectsRoute
  '/solutions': typeof SiteSolutionsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/industries': typeof SiteIndustriesRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/solutions': typeof SiteSolutionsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/projects'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/industries' | '/projects' | '/solutions' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/industries'
    | '/_site/projects'
    | '/_site/solutions'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/solutions': {
      id: '/_site/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SiteSolutionsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/industries': {
      id: '/_site/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof SiteIndustriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIndustriesRoute: typeof SiteIndustriesRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteSolutionsRoute: typeof SiteSolutionsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIndustriesRoute: SiteIndustriesRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteSolutionsRoute: SiteSolutionsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
